### ISSUE TITLE
Latest Update broke my Webmail....

### ISSUE THREAD

**Issue by kohlsalem** [afterlogic/docker-webmail-pro#2]
Hi, 
i have my pretty plain webmail automatically updated via watchtower. 

> version: "2.1"
> services:
>   webmail:
>     image: afterlogic/docker-webmail-pro
>     volumes:
>        - /opt/webmail/settings:/var/www/html/data/settings
>     ports:
>       - 8088:80
>     restart: unless-stopped 
>     labels:
>        - "com.centurylinklabs.watchtower.enable=true"

Nothing special. 6 Users. Paid license. worked fine so far. 
Since the recent automatic update run however, i can't login anymore. None of my domains users. Invalid user/pass.

The log on the docker console gives no hint at all.

Sure, i could freshly setup the container - or retrieve a backup. 

However, any idea why an update would break?  Or any idea how to track down the issue?

Thanks
Michael

**Comment by afterlogic-support** [comment]
Hello,

A few days ago we have completely rewritten docker images for our products, I'm afraid there's no backwards compatibility, the images are too different. You would need to set it anew following [the instructions](https://github.com/afterlogic/docker-webmail-pro/blob/master/README.md).

Please let us know if the new image works for you. Thank you.

**Comment by afterlogic-support** [comment]
Upon some consideration, within next few days we'll be releasing a legacy build of Docker image for WebMail Pro, so you won't have to change the working process a lot, just the image name will be different; WebMail Pro in there will be the latest version, too.
Once the legacy build is available, I'll post back here. Thanks.

**Comment by kohlsalem** [comment]
Hmm. Thanks, but i have no need for that legacy image, I just updated to your newly recommended docker compose (with the DB) and it runs fine. And i doubt anybody would have that need. If you notice the need, you already broke everything up. The new version should have gotten a new image.

What concerns me with the new install: 

- nothing is mapped as a external volume to backup/restore anymore. Is that intenion? 
- aparrantly you do not want to ensure backward compatibility of the image. So, how can i than ensure latest and secure software? For now i removed the label for autoupdate.

**Comment by afterlogic-support** [comment]
> Hmm. Thanks, but i have no need for that legacy image, I just updated to your newly recommended docker compose (with the DB) and it runs fine. And i doubt anybody would have that need. If you notice the need, you already broke everything up. The new version should have gotten a new image.

I see, fair enough.

> nothing is mapped as a external volume to backup/restore anymore. Is that intenion?

That's not entirely true, the default docker-compose.yml holds the following directive:

```
    volumes:
      - /var/lib/mysql
```

so the database content and structure are preserved. If you wish, you can adjust your copy of docker-compose.yml to also have a volume under "web:" section, something like:

```
    volumes:
      - /var/www/html/data
```

For running the image, that's not required though.

> aparrantly you do not want to ensure backward compatibility of the image. So, how can i than ensure latest and secure software? For now i removed the label for autoupdate.

I'm positive this kind of change never happens again, yet it was really necessary. The previous version of the image was using rather heavy Ubuntu with just as heavy Apache. New edition is lightweight and adopts some best practices, including advices from our users. 

We do not intend to add any more breaking changes in the future, perhaps some minor tweaks like volume definitions and package versions used. Note that the image isn't guaranteed to hold the latest version of WebMail Pro, but you can always get it by building from GitHub directly (option 1 in the instructions)

**Comment by kohlsalem** [comment]
Thanks for your help!  So i stress my luck and auto update again :-)

and upps, yes, i have overseen the volume...
