### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by My1** [afterlogic/docker-webmail-pro#3]
PHP 8.1 is kinda on Life Support being on security Updates only for about a year (and only because PHP extended the life of Versions 8.1+ with 2 years of security instead of 1.

Upgrading to at least 8.3 would ensure we are in a PHP Version in active support, although if 8.4 is supported by the software, that would obviously be ideal.

This issue applies to the other PHP-based non-legay Dockers too.

**Comment by afterlogic-support** [comment]
Good point, thank you, we'll look into this - most likely, after New Year holidays.

**Comment by afterlogic-support** [comment]
This has been completed, we've also corrected a critical issue with `mysql-native-password` setting handled differently in MySQL 8.4.
We're not updating DockerHub images just yet though, version 9.8.1 is around the corner - will update the images once it's released.

**Comment by My1** [comment]
very nice. thanks. I have sent a message directly regarding 2FA stuff in webmail pro that may or may not be relevant for security to support@afterlogic.com which was listed as your security email address a few days ago, not sure if it did arrive, can you check if it arrived to know that at least?

**Comment by afterlogic-support** [comment]
Indeed. It was passed to the product management, they'll take a look.
